### ISSUE TITLE
simulate a system with both IDPs and MDPs

### ISSUE THREAD

**Issue by Modk1996** [KULL-Centre/CALVADOS#13]
I noticed that the provided examples include systems containing only IDPs and systems containing only MDPs, but I want to simulate a system that includes both MDPs and IDPs. How should I modify the prepare.py file?

**Comment by sobuelow** [comment]
Hi!
You should be able to mix IDPs and MDPs by adding multiple `components.add()` lines in the `prepare.py` script:

```
residues_file = f'{cwd}/input/residues_CALVADOS3.csv'

components = Components(
  molecule_type = 'protein',
  charge_termini = 'both',
  fresidues = residues_file,
)

components.add(name='my_favorite_IDP', nmol=100, restraint=False, ffasta = 'input/fastalib.fasta')
components.add(name='my_favorite_MDP', nmol=100, restraint=True, pdb_folder = f'{cwd}/input', fdomains = f'{cwd}/input/domains.yaml')
```

The first (IDP) component will be read and built from a sequence fasta file (`input/fastalib.fasta`), and the second component will read in a PDB in the specified folder `pdb_folder` (make sure to have the pdb named the same as the component name). The domain boundaries are specified in `domains.yaml`.

Potentially you have to change the topology to 'grid' rather than 'slab'.

**Comment by Modk1996** [comment]
> 你好！您应该能够通过在脚本中添加多行来混合 IDP 和 MDP：`components.add()``prepare.py`
> 
> ```
> residues_file = f'{cwd}/input/residues_CALVADOS3.csv'
> 
> components = Components(
>   molecule_type = 'protein',
>   charge_termini = 'both',
>   fresidues = residues_file,
> )
> 
> components.add(name='my_favorite_IDP', nmol=100, restraint=False, ffasta = 'input/fastalib.fasta')
> components.add(name='my_favorite_MDP', nmol=100, restraint=True, pdb_folder = f'{cwd}/input', fdomains = f'{cwd}/input/domains.yaml')
> ```
> 
> 第一个 （IDP） 组件将从序列 fasta 文件 （） 中读取和构建，第二个组件将在指定文件夹中的 PDB 中读取（确保 pdb 的名称与组件名称相同）。域边界在 中指定。`input/fastalib.fasta``pdb_folder``domains.yaml`
> 
> 可能您必须将拓扑更改为 'grid' 而不是 'slab'。

Thank you very much! Your answer is really helpful.

**Comment by Modk1996** [comment]
> Hi! You should be able to mix IDPs and MDPs by adding multiple `components.add()` lines in the `prepare.py` script:
> 
> ```
> residues_file = f'{cwd}/input/residues_CALVADOS3.csv'
> 
> components = Components(
>   molecule_type = 'protein',
>   charge_termini = 'both',
>   fresidues = residues_file,
> )
> 
> components.add(name='my_favorite_IDP', nmol=100, restraint=False, ffasta = 'input/fastalib.fasta')
> components.add(name='my_favorite_MDP', nmol=100, restraint=True, pdb_folder = f'{cwd}/input', fdomains = f'{cwd}/input/domains.yaml')
> ```
> 
> The first (IDP) component will be read and built from a sequence fasta file (`input/fastalib.fasta`), and the second component will read in a PDB in the specified folder `pdb_folder` (make sure to have the pdb named the same as the component name). The domain boundaries are specified in `domains.yaml`.
> 
> Potentially you have to change the topology to 'grid' rather than 'slab'.

Thank you very much. It's really helpful!
