### ISSUE TITLE
Pytest fails R-W with github action

### ISSUE THREAD

**Issue by sobuelow** [KULL-Centre/CALVADOS#9]
Pytest fails R-W pair when running via github actions, but passes locally. @gitesei 

https://github.com/KULL-Centre/CALVADOS/actions/runs/11755243335/job/32750098364

**Comment by gitesei** [comment]
I've updated the assessment criterion so that the test now fails if the absolute deviation, |a-b|, of the OpenMM energy, a, from the reference energy, b, exceeds 1E-04 x b + 1E-08

**Comment by sobuelow** [comment]
Thanks! 🙏
